# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrganizationUser")

model_instance <- OrganizationUser$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("userId", {
  # tests for the property `userId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`userId`, "EXPECTED_RESULT")
})

test_that("username", {
  # tests for the property `username` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`username`, "EXPECTED_RESULT")
})

test_that("email", {
  # tests for the property `email` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`email`, "EXPECTED_RESULT")
})

test_that("associationType", {
  # tests for the property `associationType` (OrganizationUserAssociationType)

  # uncomment below to test the property
  #expect_equal(model.instance$`associationType`, "EXPECTED_RESULT")
})
