# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UpdateApiKey200Response")

model_instance <- UpdateApiKey200Response$new()

test_that("key", {
  # tests for the property `key` (character)
  # The updated API key

  # uncomment below to test the property
  #expect_equal(model.instance$`key`, "EXPECTED_RESULT")
})

test_that("note", {
  # tests for the property `note` (character)
  # The updated description of the API key

  # uncomment below to test the property
  #expect_equal(model.instance$`note`, "EXPECTED_RESULT")
})

test_that("enabled", {
  # tests for the property `enabled` (character)
  # Whether the API key is active or disabled

  # uncomment below to test the property
  #expect_equal(model.instance$`enabled`, "EXPECTED_RESULT")
})
