# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreateInvitationsRequest")

model_instance <- CreateInvitationsRequest$new()

test_that("emails", {
  # tests for the property `emails` (array[character])
  # List of email addresses to invite

  # uncomment below to test the property
  #expect_equal(model.instance$`emails`, "EXPECTED_RESULT")
})
