# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreateApiKey201Response")

model_instance <- CreateApiKey201Response$new()

test_that("clientKey", {
  # tests for the property `clientKey` (character)
  # The generated API key

  # uncomment below to test the property
  #expect_equal(model.instance$`clientKey`, "EXPECTED_RESULT")
})

test_that("clientSecret", {
  # tests for the property `clientSecret` (character)
  # The generated API secret

  # uncomment below to test the property
  #expect_equal(model.instance$`clientSecret`, "EXPECTED_RESULT")
})
