# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Organization")

model_instance <- Organization$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("creator", {
  # tests for the property `creator` (User)

  # uncomment below to test the property
  #expect_equal(model.instance$`creator`, "EXPECTED_RESULT")
})

test_that("visibility", {
  # tests for the property `visibility` (OrganizationVisibility)

  # uncomment below to test the property
  #expect_equal(model.instance$`visibility`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("organizationMembers", {
  # tests for the property `organizationMembers` (array[OrganizationUser])

  # uncomment below to test the property
  #expect_equal(model.instance$`organizationMembers`, "EXPECTED_RESULT")
})

test_that("contactEmail", {
  # tests for the property `contactEmail` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`contactEmail`, "EXPECTED_RESULT")
})

test_that("contactPhone", {
  # tests for the property `contactPhone` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`contactPhone`, "EXPECTED_RESULT")
})

test_that("website", {
  # tests for the property `website` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`website`, "EXPECTED_RESULT")
})

test_that("address", {
  # tests for the property `address` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`address`, "EXPECTED_RESULT")
})

test_that("canEdit", {
  # tests for the property `canEdit` (character)
  # If the current user can edit the organization

  # uncomment below to test the property
  #expect_equal(model.instance$`canEdit`, "EXPECTED_RESULT")
})

test_that("isMember", {
  # tests for the property `isMember` (character)
  # If the current user is a member of the organization

  # uncomment below to test the property
  #expect_equal(model.instance$`isMember`, "EXPECTED_RESULT")
})

test_that("created_at", {
  # tests for the property `created_at` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`created_at`, "EXPECTED_RESULT")
})

test_that("updated_at", {
  # tests for the property `updated_at` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`updated_at`, "EXPECTED_RESULT")
})
