# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Feature")

model_instance <- Feature$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("meta", {
  # tests for the property `meta` (map(object))
  # A JSON object containing meta information.

  # uncomment below to test the property
  #expect_equal(model.instance$`meta`, "EXPECTED_RESULT")
})

test_that("key", {
  # tests for the property `key` (character)
  # A key that must start with a letter, followed by any combination of letters, digits, hyphens, or underscores. For example, &#39;abc123&#39;, &#39;abc-test&#39;, or &#39;Abc_test&#39;. It cannot start with a digit.

  # uncomment below to test the property
  #expect_equal(model.instance$`key`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # A name for the feature that will appear on top of the form field

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("units", {
  # tests for the property `units` (character)
  # A name for the feature that will appear on top of the form field

  # uncomment below to test the property
  #expect_equal(model.instance$`units`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("featureType", {
  # tests for the property `featureType` (FeatureType)

  # uncomment below to test the property
  #expect_equal(model.instance$`featureType`, "EXPECTED_RESULT")
})

test_that("featureDependency", {
  # tests for the property `featureDependency` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`featureDependency`, "EXPECTED_RESULT")
})

test_that("visible", {
  # tests for the property `visible` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`visible`, "EXPECTED_RESULT")
})

test_that("possibleValues", {
  # tests for the property `possibleValues` (array[FeaturePossibleValue])

  # uncomment below to test the property
  #expect_equal(model.instance$`possibleValues`, "EXPECTED_RESULT")
})

test_that("createdAt", {
  # tests for the property `createdAt` (character)
  # The date and time when the feature was created.

  # uncomment below to test the property
  #expect_equal(model.instance$`createdAt`, "EXPECTED_RESULT")
})

test_that("updatedAt", {
  # tests for the property `updatedAt` (character)
  # The date and time when the feature was last updated.

  # uncomment below to test the property
  #expect_equal(model.instance$`updatedAt`, "EXPECTED_RESULT")
})
