# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModelExtraConfig")

model_instance <- ModelExtraConfig$new()

test_that("torchConfig", {
  # tests for the property `torchConfig` (map(object))

  # uncomment below to test the property
  #expect_equal(model.instance$`torchConfig`, "EXPECTED_RESULT")
})

test_that("preprocessors", {
  # tests for the property `preprocessors` (array[Transformer])

  # uncomment below to test the property
  #expect_equal(model.instance$`preprocessors`, "EXPECTED_RESULT")
})

test_that("featurizers", {
  # tests for the property `featurizers` (array[Transformer])

  # uncomment below to test the property
  #expect_equal(model.instance$`featurizers`, "EXPECTED_RESULT")
})

test_that("doa", {
  # tests for the property `doa` (array[Transformer])

  # uncomment below to test the property
  #expect_equal(model.instance$`doa`, "EXPECTED_RESULT")
})
