# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModelApi")

api_instance <- ModelApi$new()

test_that("CreateModel", {
  # tests for CreateModel
  # base path: https://api.jaqpot.org
  # Create a new model
  # @param model Model 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteModelById", {
  # tests for DeleteModelById
  # base path: https://api.jaqpot.org
  # Delete a Model
  # Delete a single model by its ID
  # @param id integer The ID of the model to delete
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetLegacyModelById", {
  # tests for GetLegacyModelById
  # base path: https://api.jaqpot.org
  # Get a legacy model
  # Retrieve a single model by its ID
  # @param id character The ID of the model to retrieve
  # @return [Model]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetModelById", {
  # tests for GetModelById
  # base path: https://api.jaqpot.org
  # Get a Model
  # Retrieve a single model by its ID
  # @param id integer The ID of the model to retrieve
  # @return [Model]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetModels", {
  # tests for GetModels
  # base path: https://api.jaqpot.org
  # Get paginated models
  # @param page integer  (optional)
  # @param size integer  (optional)
  # @param sort array[character]  (optional)
  # @return [GetModels200Response]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetSharedModels", {
  # tests for GetSharedModels
  # base path: https://api.jaqpot.org
  # Get paginated shared models
  # @param page integer  (optional)
  # @param size integer  (optional)
  # @param sort array[character]  (optional)
  # @param organization_id integer  (optional)
  # @return [GetModels200Response]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PartiallyUpdateModel", {
  # tests for PartiallyUpdateModel
  # base path: https://api.jaqpot.org
  # Partially update specific fields of a model
  # @param id integer 
  # @param partially_update_model_request PartiallyUpdateModelRequest 
  # @return [Model]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PredictWithModel", {
  # tests for PredictWithModel
  # base path: https://api.jaqpot.org
  # Predict with Model
  # Submit a dataset for prediction using a specific model
  # @param model_id integer The ID of the model to use for prediction
  # @param dataset Dataset 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PredictWithModelCSV", {
  # tests for PredictWithModelCSV
  # base path: https://api.jaqpot.org
  # Predict using CSV with Model
  # Submit a dataset for prediction using a specific model
  # @param model_id integer The ID of the model to use for prediction
  # @param dataset_csv DatasetCSV 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SearchModels", {
  # tests for SearchModels
  # base path: https://api.jaqpot.org
  # Search for models
  # @param query character 
  # @param page integer  (optional)
  # @param size integer  (optional)
  # @return [GetModels200Response]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
