# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PartiallyUpdateModelRequest")

model_instance <- PartiallyUpdateModelRequest$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("visibility", {
  # tests for the property `visibility` (ModelVisibility)

  # uncomment below to test the property
  #expect_equal(model.instance$`visibility`, "EXPECTED_RESULT")
})

test_that("task", {
  # tests for the property `task` (ModelTask)

  # uncomment below to test the property
  #expect_equal(model.instance$`task`, "EXPECTED_RESULT")
})

test_that("tags", {
  # tests for the property `tags` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tags`, "EXPECTED_RESULT")
})

test_that("sharedWithOrganizationIds", {
  # tests for the property `sharedWithOrganizationIds` (array[integer])

  # uncomment below to test the property
  #expect_equal(model.instance$`sharedWithOrganizationIds`, "EXPECTED_RESULT")
})
