# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PartialUpdateOrganizationRequest")

model_instance <- PartialUpdateOrganizationRequest$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("contactEmail", {
  # tests for the property `contactEmail` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`contactEmail`, "EXPECTED_RESULT")
})

test_that("visibility", {
  # tests for the property `visibility` (OrganizationVisibility)

  # uncomment below to test the property
  #expect_equal(model.instance$`visibility`, "EXPECTED_RESULT")
})
