# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FeaturePossibleValue")

model_instance <- FeaturePossibleValue$new()

test_that("key", {
  # tests for the property `key` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`key`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})
