# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FeatureApi")

api_instance <- FeatureApi$new()

test_that("PartiallyUpdateModelFeature", {
  # tests for PartiallyUpdateModelFeature
  # base path: https://api.jaqpot.org
  # Update a feature for a specific model
  # Update the name, description, and feature type of an existing feature within a specific model
  # @param model_id integer The ID of the model containing the feature
  # @param feature_id integer The ID of the feature to update
  # @param partially_update_model_feature_request PartiallyUpdateModelFeatureRequest 
  # @return [Feature]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
