# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GetAllApiKeysForUser200ResponseInner")

model_instance <- GetAllApiKeysForUser200ResponseInner$new()

test_that("clientKey", {
  # tests for the property `clientKey` (character)
  # The API key

  # uncomment below to test the property
  #expect_equal(model.instance$`clientKey`, "EXPECTED_RESULT")
})

test_that("note", {
  # tests for the property `note` (character)
  # Description of the API key

  # uncomment below to test the property
  #expect_equal(model.instance$`note`, "EXPECTED_RESULT")
})

test_that("createdAt", {
  # tests for the property `createdAt` (character)
  # Creation timestamp of the API key

  # uncomment below to test the property
  #expect_equal(model.instance$`createdAt`, "EXPECTED_RESULT")
})

test_that("expiresAt", {
  # tests for the property `expiresAt` (character)
  # Expiration timestamp of the API key (optional)

  # uncomment below to test the property
  #expect_equal(model.instance$`expiresAt`, "EXPECTED_RESULT")
})

test_that("enabled", {
  # tests for the property `enabled` (character)
  # Whether the API key is active or disabled

  # uncomment below to test the property
  #expect_equal(model.instance$`enabled`, "EXPECTED_RESULT")
})
