# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UpdateApiKeyRequest")

model_instance <- UpdateApiKeyRequest$new()

test_that("note", {
  # tests for the property `note` (character)
  # Updated description for the API key

  # uncomment below to test the property
  #expect_equal(model.instance$`note`, "EXPECTED_RESULT")
})

test_that("enabled", {
  # tests for the property `enabled` (character)
  # Set to &#x60;false&#x60; to disable the API key

  # uncomment below to test the property
  #expect_equal(model.instance$`enabled`, "EXPECTED_RESULT")
})
