# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GetModels200Response")

model_instance <- GetModels200Response$new()

test_that("content", {
  # tests for the property `content` (array[ModelSummary])

  # uncomment below to test the property
  #expect_equal(model.instance$`content`, "EXPECTED_RESULT")
})

test_that("totalElements", {
  # tests for the property `totalElements` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalElements`, "EXPECTED_RESULT")
})

test_that("totalPages", {
  # tests for the property `totalPages` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalPages`, "EXPECTED_RESULT")
})

test_that("pageSize", {
  # tests for the property `pageSize` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`pageSize`, "EXPECTED_RESULT")
})

test_that("pageNumber", {
  # tests for the property `pageNumber` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`pageNumber`, "EXPECTED_RESULT")
})
