# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrganizationInvitation")

model_instance <- OrganizationInvitation$new()

test_that("id", {
  # tests for the property `id` (character)
  # ID of the invitation

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("userId", {
  # tests for the property `userId` (character)
  # The user id associated with that invitation

  # uncomment below to test the property
  #expect_equal(model.instance$`userId`, "EXPECTED_RESULT")
})

test_that("userEmail", {
  # tests for the property `userEmail` (character)
  # Email address of the invited user

  # uncomment below to test the property
  #expect_equal(model.instance$`userEmail`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (character)
  # Status of the invitation

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("expirationDate", {
  # tests for the property `expirationDate` (character)
  # Expiration date of the invitation

  # uncomment below to test the property
  #expect_equal(model.instance$`expirationDate`, "EXPECTED_RESULT")
})
