# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PartiallyUpdateModelFeatureRequest")

model_instance <- PartiallyUpdateModelFeatureRequest$new()

test_that("name", {
  # tests for the property `name` (character)
  # A name for the feature that will appear on top of the form field

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("units", {
  # tests for the property `units` (character)
  # The units that this feature is using

  # uncomment below to test the property
  #expect_equal(model.instance$`units`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("featureType", {
  # tests for the property `featureType` (FeatureType)

  # uncomment below to test the property
  #expect_equal(model.instance$`featureType`, "EXPECTED_RESULT")
})

test_that("possibleValues", {
  # tests for the property `possibleValues` (array[FeaturePossibleValue])

  # uncomment below to test the property
  #expect_equal(model.instance$`possibleValues`, "EXPECTED_RESULT")
})
