# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Library")

model_instance <- Library$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

test_that("createdAt", {
  # tests for the property `createdAt` (character)
  # The date and time when the feature was created.

  # uncomment below to test the property
  #expect_equal(model.instance$`createdAt`, "EXPECTED_RESULT")
})

test_that("updatedAt", {
  # tests for the property `updatedAt` (character)
  # The date and time when the feature was last updated.

  # uncomment below to test the property
  #expect_equal(model.instance$`updatedAt`, "EXPECTED_RESULT")
})
