# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AuthApi")

api_instance <- AuthApi$new()

test_that("ValidateJWT", {
  # tests for ValidateJWT
  # base path: https://api.jaqpot.org
  # Validate JWT
  # Validate a JWT token
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
