# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Model")

model_instance <- Model$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("meta", {
  # tests for the property `meta` (map(object))
  # A JSON object containing meta information.

  # uncomment below to test the property
  #expect_equal(model.instance$`meta`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (ModelType)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("jaqpotpyVersion", {
  # tests for the property `jaqpotpyVersion` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`jaqpotpyVersion`, "EXPECTED_RESULT")
})

test_that("libraries", {
  # tests for the property `libraries` (array[Library])

  # uncomment below to test the property
  #expect_equal(model.instance$`libraries`, "EXPECTED_RESULT")
})

test_that("dependentFeatures", {
  # tests for the property `dependentFeatures` (array[Feature])

  # uncomment below to test the property
  #expect_equal(model.instance$`dependentFeatures`, "EXPECTED_RESULT")
})

test_that("independentFeatures", {
  # tests for the property `independentFeatures` (array[Feature])

  # uncomment below to test the property
  #expect_equal(model.instance$`independentFeatures`, "EXPECTED_RESULT")
})

test_that("sharedWithOrganizations", {
  # tests for the property `sharedWithOrganizations` (array[Organization])

  # uncomment below to test the property
  #expect_equal(model.instance$`sharedWithOrganizations`, "EXPECTED_RESULT")
})

test_that("visibility", {
  # tests for the property `visibility` (ModelVisibility)

  # uncomment below to test the property
  #expect_equal(model.instance$`visibility`, "EXPECTED_RESULT")
})

test_that("task", {
  # tests for the property `task` (ModelTask)

  # uncomment below to test the property
  #expect_equal(model.instance$`task`, "EXPECTED_RESULT")
})

test_that("actualModel", {
  # tests for the property `actualModel` (character)
  # A base64 representation of the actual model.

  # uncomment below to test the property
  #expect_equal(model.instance$`actualModel`, "EXPECTED_RESULT")
})

test_that("creator", {
  # tests for the property `creator` (User)

  # uncomment below to test the property
  #expect_equal(model.instance$`creator`, "EXPECTED_RESULT")
})

test_that("canEdit", {
  # tests for the property `canEdit` (character)
  # If the current user can edit the model

  # uncomment below to test the property
  #expect_equal(model.instance$`canEdit`, "EXPECTED_RESULT")
})

test_that("isAdmin", {
  # tests for the property `isAdmin` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isAdmin`, "EXPECTED_RESULT")
})

test_that("tags", {
  # tests for the property `tags` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tags`, "EXPECTED_RESULT")
})

test_that("legacyPredictionService", {
  # tests for the property `legacyPredictionService` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`legacyPredictionService`, "EXPECTED_RESULT")
})

test_that("extraConfig", {
  # tests for the property `extraConfig` (ModelExtraConfig)

  # uncomment below to test the property
  #expect_equal(model.instance$`extraConfig`, "EXPECTED_RESULT")
})

test_that("createdAt", {
  # tests for the property `createdAt` (character)
  # The date and time when the feature was created.

  # uncomment below to test the property
  #expect_equal(model.instance$`createdAt`, "EXPECTED_RESULT")
})

test_that("updatedAt", {
  # tests for the property `updatedAt` (character)
  # The date and time when the feature was last updated.

  # uncomment below to test the property
  #expect_equal(model.instance$`updatedAt`, "EXPECTED_RESULT")
})
