# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrganizationInvitationApi")

api_instance <- OrganizationInvitationApi$new()

test_that("CreateInvitations", {
  # tests for CreateInvitations
  # base path: https://api.jaqpot.org
  # Create new invitations for an organization
  # This endpoint allows an organization admin to create new invitations for users.
  # @param org_name character Name of the organization
  # @param create_invitations_request CreateInvitationsRequest Invitation request payload
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetAllInvitations", {
  # tests for GetAllInvitations
  # base path: https://api.jaqpot.org
  # Get all invitations for an organization
  # This endpoint allows an organization admin to get all invitations for their organization.
  # @param org_name character Name of the organization
  # @return [array[OrganizationInvitation]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetInvitation", {
  # tests for GetInvitation
  # base path: https://api.jaqpot.org
  # Get the status of an invitation
  # This endpoint allows a user to check the status of an invitation.
  # @param name character Name of the organization
  # @param uuid character UUID of the invitation
  # @return [OrganizationInvitation]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ResendInvitation", {
  # tests for ResendInvitation
  # base path: https://api.jaqpot.org
  # Resend an invitation email
  # This endpoint allows an organization admin to resend an invitation email if it has not expired. Only organization admins can access this endpoint.
  # @param org_id integer ID of the organization
  # @param id character ID of the invitation
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateInvitation", {
  # tests for UpdateInvitation
  # base path: https://api.jaqpot.org
  # Update the status of an invitation
  # This endpoint allows a user to update the status of an invitation.
  # @param name character Name of the organization
  # @param uuid character UUID of the invitation
  # @param organization_invitation OrganizationInvitation Invitation status update payload
  # @return [OrganizationInvitation]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
