# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ErrorResponse")

model_instance <- ErrorResponse$new()

test_that("message", {
  # tests for the property `message` (character)
  # Error message

  # uncomment below to test the property
  #expect_equal(model.instance$`message`, "EXPECTED_RESULT")
})

test_that("code", {
  # tests for the property `code` (integer)
  # Error code

  # uncomment below to test the property
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})
