# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Transformer")

model_instance <- Transformer$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("config", {
  # tests for the property `config` (map(AnyType))

  # uncomment below to test the property
  #expect_equal(model.instance$`config`, "EXPECTED_RESULT")
})
