# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ApiKeysApi")

api_instance <- ApiKeysApi$new()

test_that("CreateApiKey", {
  # tests for CreateApiKey
  # base path: https://api.jaqpot.org
  # Create an API Key for the User
  # Generate and return an API key for programmatic access. This API key is associated with the user and can be used for authenticating future requests.
  # @param api_key ApiKey Payload to create a new API key
  # @return [CreateApiKey201Response]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteApiKey", {
  # tests for DeleteApiKey
  # base path: https://api.jaqpot.org
  # Delete an API Key
  # Delete a specific API key associated with the authenticated user. Only the user or an admin can delete keys.
  # @param key character The API key to delete
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetAllApiKeysForUser", {
  # tests for GetAllApiKeysForUser
  # base path: https://api.jaqpot.org
  # Get All API Keys for the User
  # Retrieve all API keys associated with the authenticated user.
  # @return [array[GetAllApiKeysForUser200ResponseInner]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateApiKey", {
  # tests for UpdateApiKey
  # base path: https://api.jaqpot.org
  # Update API Key
  # Update an API key&#39;s metadata, such as its note or status (enable/disable).
  # @param key character The API key to update
  # @param update_api_key_request UpdateApiKeyRequest Payload to update API key metadata
  # @return [UpdateApiKey200Response]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
