# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModelSummary")

model_instance <- ModelSummary$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("visibility", {
  # tests for the property `visibility` (ModelVisibility)

  # uncomment below to test the property
  #expect_equal(model.instance$`visibility`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("creator", {
  # tests for the property `creator` (User)

  # uncomment below to test the property
  #expect_equal(model.instance$`creator`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (ModelType)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("dependentFeaturesLength", {
  # tests for the property `dependentFeaturesLength` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`dependentFeaturesLength`, "EXPECTED_RESULT")
})

test_that("independentFeaturesLength", {
  # tests for the property `independentFeaturesLength` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`independentFeaturesLength`, "EXPECTED_RESULT")
})

test_that("sharedWithOrganizations", {
  # tests for the property `sharedWithOrganizations` (array[OrganizationSummary])

  # uncomment below to test the property
  #expect_equal(model.instance$`sharedWithOrganizations`, "EXPECTED_RESULT")
})

test_that("createdAt", {
  # tests for the property `createdAt` (character)
  # The date and time when the feature was created.

  # uncomment below to test the property
  #expect_equal(model.instance$`createdAt`, "EXPECTED_RESULT")
})

test_that("updatedAt", {
  # tests for the property `updatedAt` (character)
  # The date and time when the feature was last updated.

  # uncomment below to test the property
  #expect_equal(model.instance$`updatedAt`, "EXPECTED_RESULT")
})
