# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrganizationApi")

api_instance <- OrganizationApi$new()

test_that("CreateOrganization", {
  # tests for CreateOrganization
  # base path: https://api.jaqpot.org
  # Create a new organization
  # @param organization Organization 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetAllOrganizationsByUser", {
  # tests for GetAllOrganizationsByUser
  # base path: https://api.jaqpot.org
  # Get all user organizations
  # @return [array[Organization]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetAllOrganizationsForUser", {
  # tests for GetAllOrganizationsForUser
  # base path: https://api.jaqpot.org
  # Get all organizations for a specific user
  # @return [array[Organization]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetOrganizationByName", {
  # tests for GetOrganizationByName
  # base path: https://api.jaqpot.org
  # Get organization by name
  # @param name character 
  # @return [Organization]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PartialUpdateOrganization", {
  # tests for PartialUpdateOrganization
  # base path: https://api.jaqpot.org
  # Partially update an existing organization
  # @param id integer 
  # @param partial_update_organization_request PartialUpdateOrganizationRequest 
  # @return [Organization]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
