# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test User")

model_instance <- User$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("username", {
  # tests for the property `username` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`username`, "EXPECTED_RESULT")
})

test_that("firstName", {
  # tests for the property `firstName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`firstName`, "EXPECTED_RESULT")
})

test_that("lastName", {
  # tests for the property `lastName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`lastName`, "EXPECTED_RESULT")
})

test_that("email", {
  # tests for the property `email` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`email`, "EXPECTED_RESULT")
})

test_that("emailVerified", {
  # tests for the property `emailVerified` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`emailVerified`, "EXPECTED_RESULT")
})
