# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ApiKey")

model_instance <- ApiKey$new()

test_that("clientKey", {
  # tests for the property `clientKey` (character)
  # The generated API key

  # uncomment below to test the property
  #expect_equal(model.instance$`clientKey`, "EXPECTED_RESULT")
})

test_that("note", {
  # tests for the property `note` (character)
  # A note for the API key

  # uncomment below to test the property
  #expect_equal(model.instance$`note`, "EXPECTED_RESULT")
})

test_that("userId", {
  # tests for the property `userId` (character)
  # The ID of the user associated with the API key

  # uncomment below to test the property
  #expect_equal(model.instance$`userId`, "EXPECTED_RESULT")
})

test_that("expiresAt", {
  # tests for the property `expiresAt` (character)
  # The expiration time of the API key (if any)

  # uncomment below to test the property
  #expect_equal(model.instance$`expiresAt`, "EXPECTED_RESULT")
})

test_that("expirationTime", {
  # tests for the property `expirationTime` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`expirationTime`, "EXPECTED_RESULT")
})

test_that("lastUsed", {
  # tests for the property `lastUsed` (character)
  # The last time the API key was used

  # uncomment below to test the property
  #expect_equal(model.instance$`lastUsed`, "EXPECTED_RESULT")
})

test_that("lastUsedIp", {
  # tests for the property `lastUsedIp` (character)
  # The IP address from which the API key was last used

  # uncomment below to test the property
  #expect_equal(model.instance$`lastUsedIp`, "EXPECTED_RESULT")
})

test_that("enabled", {
  # tests for the property `enabled` (character)
  # Whether the API key is active or disabled

  # uncomment below to test the property
  #expect_equal(model.instance$`enabled`, "EXPECTED_RESULT")
})
